version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y maven
  pre_build:
    commands:
      - echo Logging into AWS...
  build:
    commands:
      - echo Building the Java project...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully.
      - echo Uploading artifact to S3...
      - aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://java-build-artifacts-h6krzo/
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes
